### ISSUE TITLE
migrate etcd volume from efs to ebs

### ISSUE THREAD

**Issue by andrleite** [cloud104/kube-deploy#3]
We're getting this error: 2018-05-09 21:50:34.653290 W | etcdserver: timed out waiting for read index response. Analysing graphs from  EFS on cloud watch we've got low PermittedThroughput.

![image](https://user-images.githubusercontent.com/12967948/39843787-285b7222-53c3-11e8-9461-80ffe6033c05.png)

**Comment by sandromello** [comment]
Fixed by #14
